### ISSUE TITLE
Please match the format requested

### ISSUE THREAD

**Issue by dallombra** [eXpl0it3r/streamdeck-clockify#1]
Hello! When I copy the API key from my profile into the plugin, I get the following error

"Please match the format requested" - how can I fix this?

Also, I get the same error if in any of the other fields there are upper case characters?

**Comment by eXpl0it3r** [comment]
@dallombra please see the latest release I just published: https://github.com/eXpl0it3r/streamdeck-clockify/releases/tag/1.1
Let me know if this works for you! 🙂
