### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by RichSimon** [eXpl0it3r/streamdeck-clockify#12]
New to Clockify, generated an API key. Log says:

`2023-04-24 16:52:18.0585|INFO|dev.duerrenberg|32|API key successfully set`

Set up a Workspace Name ("Axis"), but no matter what I'm trying:

`2023-04-24 16:52:18.8601|WARN|dev.duerrenberg|1|Invalid settings for running timer Axis`

Not sure how to troubleshoot. Ideas? 

Perhaps the URL? Don't see where in Clockify there's a unique URL.

**Comment by RichSimon** [comment]
What should the url look like if not the default one that the code populates?

**Comment by eXpl0it3r** [comment]
I don't know exactly, as I've never seen a self-hosted instance. I assume it would be similar and additionally assume that the API is enabled on that instance.

**Comment by RichSimon** [comment]
FWIW, I tested my API key with curl and it came back fine.

**Comment by eXpl0it3r** [comment]
Can you give the in-development plugin version a try and see if it fixes the issue?  
If you use projects with different clients, consider adding the client name under the advanced settings.

- [GitHub Action](https://github.com/eXpl0it3r/streamdeck-clockify/actions/runs/4894844501)
- [Direct Download](https://github.com/eXpl0it3r/streamdeck-clockify/suites/12703799395/artifacts/681855591)

Uninstall the existing plugin first - you don't need to remove any buttons - then unzip the download and open the plugin in Stream Deck.

**Comment by eXpl0it3r** [comment]
I believe newer version shouldn't have such issues anymore. Please feel free to leave a comment with some more information if you keep running into this.
