### ISSUE TITLE
stops working after the 4th client added

### ISSUE THREAD

**Issue by pdmarf** [eXpl0it3r/streamdeck-clockify#16]
Hi, firstly let me say what a great plug in this is. Thank you. It's been running mostly fine to track 4 client projects I have set up on it. Sometime they haven't been triggering when the button is pressed, but most of the time it does. Today I added a 5th client, and it  all stopped working. The log screen shot attached is saying that AS01, the latest project can't be found, but I've checked and double checked it exists, and is identically named on clockify.  Any idea how I fix this, other than deleting it and limiting myself to 4 clients?
<img width="804" alt="Screenshot 2024-01-22 at 15 57 01" src="https://github.com/eXpl0it3r/streamdeck-clockify/assets/135653545/251e54c0-c7fa-4889-a812-5bae3e0f3e16">

**Comment by eXpl0it3r** [comment]
Glad to hear that it's been useful so far 😊

Have you updated to the 1.7 version that was released a few days ago?

I'm aware of some issues when using multiple buttons (see #11). One workaround that may help is distributing the buttons among multiple pages. Hopefully I can find a fix for this soon! 🙃

**Comment by pdmarf** [comment]
hey thanks for the quick response. Yes I'm on 1.7. I'll see if distributing works, although I'd prefer to have them all on one page. Thanks for looking into a fix, I really appreciate it.

**Comment by pdmarf** [comment]
Just some more feedback for you @eXpl0it3r, I did as you suggest and have put 3 clients only into individual files on one page. That has solved the problem. As soon as I add a 4th, it breaks. Hope that helps trouble shoot for you.

**Comment by eXpl0it3r** [comment]
Thank you for the update, this will be useful when testing the changes. 🙂

**Comment by HugoFJ** [comment]
> Just some more feedback for you @eXpl0it3r, I did as you suggest and have put 3 clients only into individual files on one page. That has solved the problem. As soon as I add a 4th, it breaks. Hope that helps trouble shoot for you.

I have exactly the same issue. 3 timers works perfectly, add a 4th and it breaks. 
No biggie as I have 3 projects per client so I can create client pages and page jumps

**Comment by eXpl0it3r** [comment]
I believe the primary issue is actually the Clockify API's rate limit. Currently building some caching to reduce the number of required queries.

**Comment by eXpl0it3r** [comment]
@pdmarf & @HugoFJ could you give the latest release 1.8 a try? 

https://github.com/eXpl0it3r/streamdeck-clockify/releases/tag/1.8

**Comment by pdmarf** [comment]
Thanks so much for releasing this! I'll give it a try and let you know

**Comment by HugoFJ** [comment]
Thankyou!

Tested it and it works with 5 buttons, there's a lag of 10 seconds before the previous timer button updates. (I can live with that)

Cheers!

**Comment by pdmarf** [comment]
Seems to be working great - I'm using multiple folders with up to 6 clients in each so far without problems. I'm also getting the 10 sec lag between buttons if while one is running, another is pressed. I've also noticed that often the clockify app (mac) won't register a button press, although the web app shows the timer is working fine. I have to restart the desktop app and then it show the timer running.

**Comment by eXpl0it3r** [comment]
Glad to hear that it's generally working.

Yes, the 10s delay is one of the trade-off to reduce the amount of calls to the API. Will be thinking if there's some alternative.

> PS... if you had a 'buy me a coffee' or tip option, I defo contribute as a thank you for such a great plug in.

I've been considering setting up GitHub Sponsors, but haven't done so far, maybe one day. Appreciate it though! 🙂
