### ISSUE TITLE
Installtion under 6.5.0

### ISSUE THREAD

**Issue by HugoFJ** [eXpl0it3r/streamdeck-clockify#17]
I'm struggling to work out how, and if it's even possible to install this plugin under streamdeck OS 6.5.0
 
 Have I missed something obvious? Thanks in advance!

**Comment by eXpl0it3r** [comment]
You can just double click the plugin and it should open in StreamDeck.

If the plugin file extension hasn't yet been associated with StreamDeck, then you should be able to just drag an drop the file onto the StreamDeck software.

**Comment by HugoFJ** [comment]
Amazing!

Thanks you, so easy. Is it worth adding that step to the GitHub readme for other numpties like me?
________________________________

**Comment by HugoFJ** [comment]
BTW keep up the amazing work. I used to use Toggl, but since the StreamDeck plugin is not longer supported I'm delighted that I was able to swithc to clockify :-)

**Comment by eXpl0it3r** [comment]
> Is it worth adding that step to the GitHub readme for other numpties like me?

Yeah, certainly. I was surprised, I hadn't added it already.

> keep up the amazing work

I'll try! 🙂 

> I used to use Toggl, but since the StreamDeck plugin is not longer supported

Oh, really? Sad to hear, because last I interacted with the author of the Toggl plugin, he said, that Toggl is looking into releasing a new version kind of officially. Too bad that it apparently just died now...

**Comment by HugoFJ** [comment]
Yeah sadly Tobias archived the repo in October 2023 
"Unfortunately, I am lacking time and energy to actively uphold development of this plugin"
There's been a change with the API as far as I can work out so now it's inevitably fallen over.
