### ISSUE TITLE
doesn't work with multiactions

### ISSUE THREAD

**Issue by rkamaladasa** [eXpl0it3r/streamdeck-clockify#2]
Hi, 
Great plugin. It works great as a regular button but I can't seem to search and add it with Stream Deck Multi Actions. Would be great if you can add that functionality. Thanks!

**Comment by eXpl0it3r** [comment]
Glad you like it!

Oh, I haven't tried that and would have expected this to just work out of the box, but let me have a look, what's going on there. 🙂

**Comment by eXpl0it3r** [comment]
Figured it out, just needed a config change in the manifest

Fixed with 792cf7eb1978dee7d457d3d1950e49e489f99392

@rkamaladasa check out the latest release: https://github.com/eXpl0it3r/streamdeck-clockify/releases/latest
