### ISSUE TITLE
Title Format doesn't work

### ISSUE THREAD

**Issue by jordanalwon** [eXpl0it3r/streamdeck-clockify#20]
The title formatting option doesn't work. Any information will be ignored. 
I ran the content `{timer}` on Windows 10 with Stream Deck version 6.6.0

**Comment by jordanalwon** [comment]
If I don't set a Title it works. But if I set a title and set the title format to {timer} I expect the title before I start the timer and the timer value after starting the timer. The title overrides all configurations in the title format and maybe the option for title is missing in the format options.
btw nice work :) 
![grafik](https://github.com/eXpl0it3r/streamdeck-clockify/assets/49233087/768527d4-116c-4256-9f0a-16469743baa2)

**Comment by eXpl0it3r** [comment]
As far as I’m aware, if you set a title, there isn’t anything I can do in code to override it.
You could use the timer name and the timer to show both.

But what I’m hearing is, that you’d want to have a different text while idle vs when the timer is running, is that correct?

**Comment by jordanalwon** [comment]
I think that the problem for me at first was that I filled in the fields from top to bottom and then, despite entering title format, these entries were ignored.
On the other hand, it would of course be a nice feature if there was a self-selectable text on the button at the beginning for the overview and after activation this text changes to the formatted text.
I could imagine having two "title formats" fields, one determining the idle status and the other during activation. In addition to the predefined variable fields (e.g. {timer}), other text without connection to other fields should also be permitted.

**Comment by eXpl0it3r** [comment]
IMHO there's currently enough customization available and I don't necessary want to make the interface more complicated.

If you write a title, you're overwritting any customization.

If you just want the timer name when idle, you can still add the timer itself, and it won't show if it's not running. This should give you the option to a name show when the timer isn't running and the name + timer, when the timer is running. Note, that you can also hard code any other string in the formatting text area incase you don't want to use the timer name.

As such, I'll close this.

If you think there's still merit in some specific customization, please open a new issue with a detailed description of how you'd like it to be.
