### ISSUE TITLE
Question / Feature

### ISSUE THREAD

**Issue by killianconsulting** [eXpl0it3r/streamdeck-clockify#25]
Am I missing something? (Probably) Or is there no way to set the words (title) on the button without blocking the timer? 

If I leave Title and Title Format empty then it displays the Timer Name with a clock. This is great, but if I have buttons for multiple clients, there is no way to tell which button is for what client if the Timer Name (e.g. Meeting) is all the same. But since the Timer Name is linked to the Description in Clockify, if I tried to change it to something like an abbreviation of the Client Name (MOR Meeting) then in Clockify it is going to look really redundant with the client name in the description while it is already connected to a client (and in my case the client name in the project as well). 

Could Timer Name and Description be separated so we could have the Timer Name on the button without overriding the clock but still designate what should be in the Description for that button press? 

I can elaborate more if I'm not being clear.

**Comment by eXpl0it3r** [comment]
Check the Advanced options in the readme: https://github.com/eXpl0it3r/streamdeck-clockify

You can fully customize what is shown on the button. 🙂

**Comment by killianconsulting** [comment]
I tried that but then the timer on the button doesn't work.

**Comment by killianconsulting** [comment]
![image](https://github.com/user-attachments/assets/c4918114-010e-4bb4-92db-d7c38158662b)

Yes, this will customize the button it was overriding the same way the Title field would.

**Comment by eXpl0it3r** [comment]
In the format you can write something like:

```
MOR
{timer}
```

`{timer}` will be replaced by the timer values

**Comment by killianconsulting** [comment]
That's the piece that I was missing. Thank you!

**Comment by eXpl0it3r** [comment]
Any suggestion that would've made it more clear?

**Comment by killianconsulting** [comment]
tbh, I'm not certain. I don't even think I saw the timer property so that's a me problem (RTFS) but maybe an example of how they can be inserted with something else verses being used independently.
