### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by frunika** [eXpl0it3r/streamdeck-clockify#4]
Hey Lukas,

thank's for your work! I hope you will continue to work on this plugin :)

Sadly, the plugin won't work on MacOS. Stream Deck Software reports, that "This custom action can't be installed on this operating system"

![image](https://user-images.githubusercontent.com/38660441/152527240-bff2f13e-48f4-4723-81ff-f91e0596d556.png)

I'm happy to help developing an maintaining this plugin, if you need and want help :)

**Comment by eXpl0it3r** [comment]
Yes, macOS support has been in the back of my head.
As it's currently built with .NET 5 I'll have to investigate, what is required to get things compatible.

If you have experience in that area, I'd be more than happy to receive some help. 🙂 

I do have access to Apple devices, but haven't really done anything with .NET on macOS 😅 
Not developed anything for Stream Deck on macOS

**Comment by eXpl0it3r** [comment]
Will also have to make sure that the "smaller" third-party libraries work correctly on macOS

- https://www.nuget.org/packages/Clockify.Net/
- https://www.nuget.org/packages/StreamDeck-Tools/

The alternatively would be to move everything to JavaScript instead 😅

**Comment by eXpl0it3r** [comment]
Got some tips on how to approach this. Apparently once an just store both macOS and Windows versions side by side, which make things larger, but also easier, as I wouldn't have to build a cross-platform application.

**Comment by frunika** [comment]
Sound like a first way to go. Unfortunately I'm barely experienced with .NET and its universe :(
An neither have experience with Steam Deck apps :D

Maybe I'm at least able to help specify new features and do some research about the API stuff

**Comment by frunika** [comment]
Let me know if there is something to do, test or document

**Comment by eXpl0it3r** [comment]
Just a brief progress update

I've spent quite some time trying to get the plugin working on macOS.
I got it to compile and could package it and even install it on the Stream Deck on macOS, but for some unexplainable reason the WebSocket connection between the Stream Deck & the plugin fails/disconnects.
Unfortunately the developer of Bar Raider's SDK Tools also didn't know what's going on.

The next step is to build the underlying streamdeck-connection-client and SDK tools manually, so I can add additional logging to understand what is actually going on. I guess the alternative would be to somehow debug it, but I don't know how to do this effectively, as the plugin shuts down rather quickly, so attaching to the process can be tricky.

**Comment by frunika** [comment]
Thanks for the update! Sounds annoying... :(

**Comment by frunika** [comment]
Hey Lukas,

how is it going? Any success in debugging?

**Comment by eXpl0it3r** [comment]
Nope, unfortunately I didn't invest any additional time for now.
Might find a slot this evening. 😉

**Comment by eXpl0it3r** [comment]
Had to drill open the streamdeck-client-csharp library and found the issue, which I should have known about since the beginning, as I was told to include the runtime.osx.10.10-x64.CoreCompat.System.Drawing package from the start and since it compiled without it, I thought I would be fine...

Now looking into clean this up and seeing how I can package the plugin that works on both Windows and macOS.

**Comment by eXpl0it3r** [comment]
Just published the 1.4 release that should be compatible with Windows and macOS.
Let me know if it works!

https://github.com/eXpl0it3r/streamdeck-clockify/releases/tag/1.4

**Comment by frunika** [comment]
I'm excited 😆

Will test it asap!

**Comment by eXpl0it3r** [comment]
Does it work? 😅

**Comment by eXpl0it3r** [comment]
Woho! 🥳 

Glad to hear 🙂
