### ISSUE TITLE
Tasks integration

### ISSUE THREAD

**Issue by Jackaroo91** [eXpl0it3r/streamdeck-clockify#5]
Hi Lukas, 
thanks for your work and sharing it. Was able to add it to Streamdeck right away. 
However I´m missing a very important feature for timetracking in our company. For all projects you have to name a task to be able to stop the timer but tasks are not taken into account here. Are there any plans to integrate that feature? 
Sadly I can´t use it for now, looking forward to your answer. 
Cheers, Frederic

**Comment by eXpl0it3r** [comment]
Unless I misunderstand what you mean with "task", I believe you can already do this, by specifying a "Timer Name".

If you check the video below, you can see that I enter "Do Work!" as Timer Name and it appears as timer description/name/task

https://user-images.githubusercontent.com/920861/132741561-6f9f3ff0-a920-408d-8279-579840ce0a6b.mp4

**Comment by Jackaroo91** [comment]
The time entries are build up like this:
Workspace -> check
Project -> check
Task -> not available
Description -> check

![grafik](https://user-images.githubusercontent.com/99913542/154668705-c465f9f8-3cec-488e-b9f2-81ea69bfd8a3.png)

So this is the timer activated via Stream Deck
![grafik](https://user-images.githubusercontent.com/99913542/154668883-a92d2d50-d304-458e-812e-78d6730bd6bf.png)

And this is how it should be when Tasks are available
![grafik](https://user-images.githubusercontent.com/99913542/154669119-f138cd7c-8bda-4469-8586-588d5fd1530a.png)

Hope my explanation is good enough, any further questions I´m more than happy to help.

**Comment by eXpl0it3r** [comment]
Oh, I hadn't seen this before. Yes, I'll look into it 🙂

**Comment by eXpl0it3r** [comment]
Would you expect that if you enter a Task that doesn't exist yet and start the timer, that the task is created?

**Comment by eXpl0it3r** [comment]
Just released a new version that brings support for tasks: https://github.com/eXpl0it3r/streamdeck-clockify/releases/tag/1.3

Let me know if this is what you hoped for or if there's anything else that should be added -- feel free to open a new issue then.

**Comment by Jackaroo91** [comment]
That was quick, thanks for the update, it works perfectly :)

**Comment by eXpl0it3r** [comment]
Glad to hear that! 😊
