### ISSUE TITLE
Add support for client field

### ISSUE THREAD

**Issue by eXpl0it3r** [eXpl0it3r/streamdeck-clockify#7]
> Can you add a client field?  My company uses the same project name over and over, but the thing that changes things is the client name.  If I have a unique project name, it works well, but if my project name is the same across multiple clients, it fails.

_Originally posted by @ARegalbuto in https://github.com/eXpl0it3r/streamdeck-clockify/issues/6#issuecomment-1366199558_

**Comment by eXpl0it3r** [comment]
Interesting, haven't used clients before, but I'll see what I can do.  
Am I understanding your correctly, that you'll have x projects with the same name, but different clients assigned?

**Comment by EDIflyer** [comment]
Hi @eXpl0it3r just wondered if you'd had a chance to look at adding the Client or Tag options yet - from what I can see there seems to be the following fields when creating an entry, which are also available as filters:

![image](https://github.com/eXpl0it3r/streamdeck-clockify/assets/13610277/8bc72ed2-3731-45af-89dd-05d94090734f)

- Team
- Client
- Project
- Task
- Tag
- Description

I was thinking the last one was more something you'd add later on the website but to be able to set the other ones via Stream Deck would be fantastic :)

**Comment by eXpl0it3r** [comment]
Can you give an example of how you use the Tag field? So I can understand its use case a bit better.

Currently stuck trying to solve #11 and #12, but might just release the re-write and add new options.

**Comment by EDIflyer** [comment]
As mentioned in #14 I tend to use the same generic project name for different clients, which works fine for splitting work by type for each client, but if I wanted to look at the broader picture (e.g., all time spent on email, or all time spent on virtual meetings) across all clients then using tagging functionality would seem to be the best/easiest way to do it?

**Comment by eXpl0it3r** [comment]
I've merged support for clients, but haven't documented it, nor made a new release, if you're in a hurry, you can pick up the automated build here: https://github.com/eXpl0it3r/streamdeck-clockify/actions/runs/5980730152

**Comment by eXpl0it3r** [comment]
I've published a new release: https://github.com/eXpl0it3r/streamdeck-clockify/releases/tag/1.7
