### ISSUE TITLE
Option to have title text only be current time

### ISSUE THREAD

**Issue by HughMacdonald** [eXpl0it3r/streamdeck-clockify#9]
I've just started using this plugin, and it's awesome.

One feature that I think would be really useful would be to have the option to have the title text on the button only be the current time being logged.

As far as I can tell, there are currently 4 options:

1. Project Name, Task Name, Time
2. Timer Name (if set)
3. Title (if set)
4. Nothing (if Show Title is turned off)

I've got my buttons set up with an icon to show what it is for, but it would be great to be able to also show the current time on this view, without also showing the Project Name and Task Name.

Thanks

**Comment by HughMacdonald** [comment]
I've actually already started having a look at how it might be implemented myself.

My initial thought was to have a checkbox called something like "Timer Only Title". However, a more power-user approach might be to have a multi-line title format string that would default to something like "{projectName}\n{taskName}\n{timer}" that could then be edited to show only the fields that the user wanted to see.

**Comment by HughMacdonald** [comment]
If the "Title Format" approach sounds good to you, I'm going to give it a go myself. I've not done any StreamDeck plugin dev before, but I'm pretty comfortable with C#

**Comment by HughMacdonald** [comment]
That's awesome that you've got it all set up with GH Actions.

I'm thinking it could be hidden under an "Advanced" drop-down. The main tricky part would be what to do if they use a key that doesn't exist, or don't have matching {}s, etc...

**Comment by eXpl0it3r** [comment]
I'd see two options:
- Silently fail and show the next best interpretation
- Replace the whole output with some "ERROR" text

The first can easily hide some issues, while the second might not really be verbose enough. One could log the output, but those logs aren't really easily accessible. Maybe there's a bit space in the inspector view to show a slightly extended error message.

I suggest, you just give it a go and see with what you end up 🙂

**Comment by HughMacdonald** [comment]
I need to get back to actual work now, so may take another look at this tomorrow.

Do you tend to work by pushing up to GH regularly and then using the CI-generated plugin to test with? That feels like a really awkward way of testing as you go

**Comment by eXpl0it3r** [comment]
I've just recently added GitHub Actions. It's honestly not much more awkward than working locally, as you need to build/publish, then use the plugin packaging tool to create a new plugin, then replace the existing plugin, by either uninstalling it manually and reinstalling it, or closing StreamDeck deleting the plugin directory and install the new plugin.

There's the [`install.ps1`](https://github.com/eXpl0it3r/streamdeck-clockify/blob/master/install.ps1) script to automate some of that, but it's still cumbersome. The GitHub Action is at least very useful, so I don't have to do the same dance on two platforms. 😄

**Comment by HughMacdonald** [comment]
The one thing that I'm realising might be tricky is ensuring that adding this setting doesn't change functionality for people using the plugin.

The way I'm thinking of doing this, it could only leave blank where an element isn't included. But in the current code, if timerName is set, then it uses it (and nothing else), whereas if it isn't set, then it uses projectName and taskName

**Comment by HughMacdonald** [comment]
BTW - I think I spotted a typo in the code. In PluginSettings.cs, line 20, the C# property is `TimeName`, but the Json propert name and PropertyInspector have it as `timerName`

**Comment by HughMacdonald** [comment]
I've had a quick go at this. The one thing that I haven't figured out is how to get the value from the UI replicated into the C# property. It may be because I'm using a textarea.

I'm just using string.Replace(), so it will just show {blah} if something is used in the format that isn't supported.

https://github.com/eXpl0it3r/streamdeck-clockify/compare/master...HughMacdonald:streamdeck-clockify:master

**Comment by eXpl0it3r** [comment]
That's just the default font, I believe. I guess one can configure it somehow and/or Spotify does some additional magic 😄 

For Clockify you can change it:

![image](https://user-images.githubusercontent.com/920861/223528341-ef105ee0-bf43-4e57-99ff-03c12ef03fd6.png)

**Comment by eXpl0it3r** [comment]
Took me a bit to figure it out, but you have to tell the Barraider integration, that you want the textarea to be a property by setting the `sdProperty` class and then need to update the settings when changing the contents of the textarea by adding `oninput="setSettings()"`.

Feel free to take or re-implement my commit 🙂 

https://github.com/eXpl0it3r/streamdeck-clockify/compare/feature/format-title
